### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by xuhcc** [editorconfig/editorconfig-geany#13]
Please consider adding a version tag. I'm on Arch Linux and there is a package with version 0.1.1: https://aur.archlinux.org/packages/editorconfig-geany/. I also found this gentoo package https://packages.gentoo.org/packages/dev-util/editorconfig-geany with version 0.1. So the next version could be 0.2.0.

**Comment by xuhdev** [comment]
Done!

**Comment by xuhcc** [comment]
Thanks!
