### ISSUE TITLE
Unable to Install Editorconfig for Geany on Raspbian Jessie (Raspberry Pi device)

### ISSUE THREAD

**Issue by yogeshmr** [editorconfig/editorconfig-geany#5]
Hi, 

I am trying to install editorconfig on Raspberry Pi3 with Raspbian Jessie Pixel OS which comes with geany pre-installed.

I have performed step 1 of Installation and I am unable to follow the instruction in step 2 "Download EditorConfig plugin for Geany source tree, and you will find a Makefile in the root."

I am unable to locate any Make or Makefile inside the directories where geany is present. In my system, when I give "whereis geany", it lists below paths:

/usr/bin/geany     --> This is not a directory
/usr/include/geany
/usr/share/geany/
/usr/share/man/man1/geany.1.gz

I cannot find a Makefile in any of the above locations.

Please find below output of few more commands:
$whereis editorconfig
editorconfig: /usr/include/editorconfig
$ echo $(pkg-config --variable=libdir geany)/geany
/usr/lib/arm-linux-gnueabihf/geany
$ echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
 
Thanks,
Yogesh

**Comment by xuhdev** [comment]
The Makefile is in the source code archive: https://github.com/editorconfig/editorconfig-geany/archive/master.tar.gz

**Comment by yogeshmr** [comment]
Hi xuhdev, Thanks a lot... I got the plugin installed .. :)
