### ISSUE TITLE
Why we need to compile it?

### ISSUE THREAD

**Issue by BarbzYHOOL** [editorconfig/editorconfig-geany#7]
No way to install it easily like all the other geany plugins?

**Comment by xuhdev** [comment]
I'm not aware of any geany plugin that does not require compilation. Do you mean that you wanna this plugin to be packaged by a distribution, such as Debian/Ubuntu or Fedora?

**Comment by BarbzYHOOL** [comment]
I spoke of plugins from here https://plugins.geany.org/ I didn't have to manually compile

**Comment by xuhdev** [comment]
They are from [here](https://github.com/geany/geany-plugins).  All of them require compilation. I think you meant why this is not yet packaged by a distribution. Which OS are you on?

**Comment by BarbzYHOOL** [comment]
Of course that's what I meant :P 
I'm on Ubuntu 14.04

**Comment by xuhdev** [comment]
Please request a package from Debian: https://wiki.debian.org/RFP

**Comment by BarbzYHOOL** [comment]
They won't do shit or it will take forever or be on debian 9 and ubuntu 18.04 I bet
But thank you for info, I will compile
